### ISSUE TITLE
Drinking the "Nether Star Lager Mug" in creative will result in loss of creative flight

### ISSUE THREAD

**Issue by MindFaer** [itzme1on/AlcoCraft-Plus#1]
As title suggests, drinking the nether star lager gives the flight effect, but when it runs out of time, the creative flight is removed until you change gamemode, and then change it back to creative.

**Comment by itzme1on** [comment]
Hello! Thank you for bug report. Please, use [this form](https://github.com/itzme1on/AlcoCraft-Plus/issues/new/choose) and create new bug report again.
