### ISSUE TITLE
Хмель не сажается. Пиво при поставке на блок имеет только русскую локализацию, а английской версии нема.

### ISSUE THREAD

**Issue by NideVice** [itzme1on/AlcoCraft-Plus#11]
### Steps to Reproduce

1. Разлить воду возле блока земли/травы/подзола/мицелия
2. Тыкнуть мотыгой по этому блоку земли/травы/подзола/мицелия
3. Тыкнуть семенами  хмеля по грядке
4. ???
5. PROFIT
----
1.Поставить пиво на землю
2.Увидеть результат в JADE
![image](https://github.com/itzme1on/AlcoCraft-Plus/assets/52417295/a72341c9-696c-4117-a1dd-0bc3d5e6a2d0)

### Expected Behavior

семена посадятся, пиво будет английским

### Actual Behavior

тема ишуи

### Your Minecraft version

1.19.2 forge

### Your error log

ну, нема, ибо баги не крашат

### Additional Comments

Доделай, пж

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
Хмель нужно сажать на нижнюю часть блока, а не на грядку. Для второго бага создай новый issue, пожалуйста.
