### ISSUE TITLE
Совместимость с Jade

### ISSUE THREAD

**Issue by NideVice** [itzme1on/AlcoCraft-Plus#12]
### Steps to Reproduce

1. Поставить пиво на блок
2. Посмотреть на него
![image](https://github.com/itzme1on/AlcoCraft-Plus/assets/52417295/c6a20aac-105f-49d5-9670-f76f98f4d16f)

### Expected Behavior

Название "блока пива" будет локализовано под английский

### Actual Behavior

Название "блока пива" на русском

### Your Minecraft version

1.19.2

### Your error log

лога нет.

### Additional Comments

Это скорее не баг, а отсутствие совместимости, но писать issues по этому поводу можно тока в категорию баг

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
Привет! Большое спасибо, что сообщил от этом. 

Ты прав ー это не баг, я просто в последней версии использовал PR человека, который помог пофиксить предыдущие косяки. Скорее всего, он просто запуллил старую ветку. 

Будет исправлено в следующей версии.
