### ISSUE TITLE
Chorus ale mug gives the effect of Luck instead of Levitation 

### ISSUE THREAD

**Issue by DrBardak** [itzme1on/AlcoCraft-Plus#13]
### Steps to Reproduce

1. Put necessary materials in keg
2. Brew Chorus ale
3. Extract Chorus ale with the mug
4. Drink Chorus ale mug
5. Get the effect of luck instead of levitation 

### Expected Behavior

Get frome Chorus ale mug effect of levitation 

### Actual Behavior

Chorus ale mug gives effect of luck 

### Your Minecraft version

1.19.2 Forge

### Your error log

N\A

### Additional Comments

Mod was added to the server. 

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
Hello! Thank you so much for your issue.

This bug will be fixed in next update.
