### ISSUE TITLE
Seeds/hops not stackable

### ISSUE THREAD

**Issue by Aceplante** [itzme1on/AlcoCraft-Plus#2]
### Steps to Reproduce

Download alcocraft
Download alcocraft Plus
bread grass
observe
Plant seeds
wait
collect hop
observe

### Expected Behavior

Seeds to stack

### Actual Behavior

they do not stack

### Your Minecraft version

1.18.2 forge

### Your error log

N/A

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
**AlcoCraft+** is not an addon for the original **AlcoCraft** mod. AlcoCraft+ is a full-fledged mod. The seeds of the original mod and this fork have different identifiers, so the seeds cannot stack.
