### ISSUE TITLE
Multiple random mugs on brewing

### ISSUE THREAD

**Issue by Aceplante** [itzme1on/AlcoCraft-Plus#3]
### Steps to Reproduce

Brew Kvass
observe

### Expected Behavior

To only get kvass/the ale i tried to brew

### Actual Behavior

I got the nether lager/chorus ale, and others

### Your Minecraft version

1.18.2 forge

### Your error log

N/A

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
Send your mods list. The same applies to issue #2

**Comment by Aceplante2** [comment]
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
[Potions Overhauled (by JohnSmith_474)](https://www.curseforge.com/minecraft/mc-mods/potions-overhauled)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[NBT Autocomplete (by mt1006x)](https://www.curseforge.com/minecraft/mc-mods/nbt-autocomplete)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Skeleton Rising (by PlacekDobryPan)](https://www.curseforge.com/minecraft/mc-mods/skeleton-rising)
[Atmospheric Paintings Pack for FORGE and FABRIC (by JestemZbychu)](https://www.curseforge.com/minecraft/mc-mods/jess-painting-pack)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[No Telemetry (by kb1000)](https://www.curseforge.com/minecraft/mc-mods/no-telemetry)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[End Portal Parallax (by rune_smith98)](https://www.curseforge.com/minecraft/mc-mods/end-portal-parallax)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[First-person Model (Forge/Fabric) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/first-person-model)
[Wildfire's Female Gender Mod (Forge) (by WildfireRomeoMC)](https://www.curseforge.com/minecraft/mc-mods/female-gender-forge)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[AlcoCraft+ (by itzme1on)](https://www.curseforge.com/minecraft/mc-mods/alcocraft)
[Leave My Bars Alone (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/leave-my-bars-alone)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Lucent (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/lucent)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Colorful Health Bar (Updated) (by Rikka_Kitani)](https://www.curseforge.com/minecraft/mc-mods/colorful-health-bar-updated)
[Difficult Spawners (by InfernalEclipse)](https://www.curseforge.com/minecraft/mc-mods/difficult-spawners)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Elytra Physics (by ImJ0shh_)](https://www.curseforge.com/minecraft/mc-mods/elytra-physics)
[Alcocraft: Beer & Stuff (by hadrus91)](https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff)
[Simple Sitting (by Milvvie)](https://www.curseforge.com/minecraft/mc-mods/simple-sitting)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[S33R Butterfly Paintings (by s33r_of_pyr3)](https://www.curseforge.com/minecraft/mc-mods/s33r-butterfly-paintings)
[Eating Animation [Forge] (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-forge)
[Remove Reloading Screen (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rrls)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Cultural Delights (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights)
[MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Cake Chomps (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/cake-chomps)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Keyboard Wizard (by mrnerdy42)](https://www.curseforge.com/minecraft/mc-mods/keyboard-wizard)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[REBIRTH: The Cosmetic Project (by DrowsyXBear)](https://www.curseforge.com/minecraft/mc-mods/rebirth)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[InvMove (by PieKing1215)](https://www.curseforge.com/minecraft/mc-mods/invmove)
[Texels Paintings (by builtwithtexels)](https://www.curseforge.com/minecraft/mc-mods/texels-paintings)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Pop! (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/bubbles)
[MOA DECOR: TOYS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-toys)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[AstikorCarts [Horse Carts] (by pau101)](https://www.curseforge.com/minecraft/mc-mods/astikorcarts)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[ReBlured (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/reblured)
[Flower Patch (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/flower-patch)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Mana and Artifice (by AWildCanadianEh)](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Name Pain (by naqaden)](https://www.curseforge.com/minecraft/mc-mods/name-pain)
[Soul fire'd (by Crystal_Spider_)](https://www.curseforge.com/minecraft/mc-mods/soul-fired)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Balanced Crates (by LettuceMuncher)](https://www.curseforge.com/minecraft/mc-mods/balanced-crates)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)

**Comment by itzme1on** [comment]
Just delete hadrus' AlcoCraft: Beer and stuff. You don't need to use it. AlcoCraft+ is fork of hadrus' mod and for it to work, you do not need to install the original mod.

**Comment by itzme1on** [comment]
Has the error been fixed?

**Comment by Aceplante** [comment]
Unfortunately I am on a server and they do not want to delete the mod for fear of any corruption, so I am not sure.

**Comment by FoxyFox909** [comment]
This bug is happening to me on 1.18.2.

It appears to be affecting multiple brewing recipes.

I do not have Hadrus's Alcocraft, ONLY ``alcocraftplus-1.18.2-forge-1.0``
