### ISSUE TITLE
Nether star lager mugs do not brew

### ISSUE THREAD

**Issue by ghost** [itzme1on/AlcoCraft-Plus#8]
### Steps to Reproduce

1. get necessary materials
2. put in keg with water
3. brew
4. get nothing!!!! and it takes your mugs

### Expected Behavior

get nether star lager mug

### Actual Behavior

the keg completly bugs and it looks like water is in there and when you try to use mugs to take it out it deletes the mugs

### Your Minecraft version

1.19.2 forge

### Your error log

https://gist.github.com/mnmwolf/664aca711175d9a4682142f7f2625695

### Additional Comments

at first i tried brewing them in my server, but it did not work. I then made a separate profile in curseforge with just AlcoCraft+ in it and the bug was still there

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by itzme1on** [comment]
I will delete Nether star lager in new mod versions. I think flight is very cheating.
